blank_issues_enabled: false
contact_links:
  - name: Mony Wiki
    url: https://github.com/Invvk/Mony/wiki
    about: Mony page, please view it before asking for help
  - name: Support Discord
    url: https://discord.gg/xcFJvXYsnD
    about: Our support Discord, please ask questions and seek support here.